version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    groups:
      all-action:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"
        - "major"
  - package-ecosystem: docker
    directories: 
      - "/docker/**"
    schedule:
      interval: daily
    groups:
      all-docker:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"
        - "major"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      all-gomod:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"
        - "major"
  - package-ecosystem: pip
    directories: 
      - "/presets/**"
    schedule:
      interval: daily
    groups:
      all-python:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"
        - "major"
