version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore"

  - package-ecosystem: docker
    directories:
      - "/docker/adapters"
      - "/docker/datasets"
      - "/docker/examples/custom-model-integration"
      - "/docker/presets/models/tfs-onnx"
      - "/docker/presets/models/tfs"
      - "/docker/ragengine"
      - "/docker/ragengine/service"
      - "/docker/workspace"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"

  - package-ecosystem: pip
    directories:
      - "/presets/ragengine"
      - "/presets/workspace/dependencies"
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"

  - package-ecosystem: "npm"
    directories:
      - "/website"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
