// Copyright (c) KAITO authors.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by hack/gen-chunksizes; DO NOT EDIT.
// Source: pkg/cache/dacs/chunksize/models.yaml
// Regenerate with: make generate-chunksizes
//
// Each recommendation is the modal per-tensor byte size from the model's
// safetensors headers (the size the most tensors share, with any tensor larger
// than 32 MiB counted as 32 MiB and the result floored at 2 MiB); see the table
// above each entry.

package chunksize

// recommendedChunkSizes maps a KAITO runtime model name to the recommended
// run:ai streamer chunk byte size (RUNAI_STREAMER_CHUNK_BYTESIZE). Keys are the
// lowercased final path segment of the HuggingFace repo — the value KAITO sets
// as PresetParam.Name at runtime (e.g. "mistralai/Mistral-7B-v0.3" ->
// "mistral-7b-v0.3"); the short preset name is added as an alias when it
// differs. Look up via Recommended, which normalizes its argument.
var recommendedChunkSizes = map[string]int{
	// === qwen3-coder-30b-a3b-instruct ===
	// repo:    Qwen/Qwen3-Coder-30B-A3B-Instruct @ b2cff646eb4bb1d68355c01b18ae02e7cf42d120
	// tensors: 18,867   total: 61,064,245,248 B (56.87 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//       6144         3,145,728   3.000 MiB  BF16   (2048, 768)      model.layers.N.mlp.experts.N.down_proj.weight  <= modal (most tensors at this size)
	//       6144         3,145,728   3.000 MiB  BF16   (768, 2048)      model.layers.N.mlp.experts.N.gate_proj.weight  <= modal (most tensors at this size)
	//       6144         3,145,728   3.000 MiB  BF16   (768, 2048)      model.layers.N.mlp.experts.N.up_proj.weight  <= modal (most tensors at this size)
	//         48        16,777,216  16.000 MiB  BF16   (2048, 4096)     model.layers.N.self_attn.o_proj.weight
	//         48        16,777,216  16.000 MiB  BF16   (4096, 2048)     model.layers.N.self_attn.q_proj.weight
	//          1       622,329,856  593.500 MiB  BF16   (151936, 2048)   lm_head.weight
	//          1       622,329,856  593.500 MiB  BF16   (151936, 2048)   model.embed_tokens.weight
	//         48         2,097,152   2.000 MiB  BF16   (512, 2048)      model.layers.N.self_attn.k_proj.weight
	//         48         2,097,152   2.000 MiB  BF16   (512, 2048)      model.layers.N.self_attn.v_proj.weight
	//         48           524,288   0.500 MiB  BF16   (128, 2048)      model.layers.N.mlp.gate.weight
	//         48             4,096   0.004 MiB  BF16   (2048,)          model.layers.N.input_layernorm.weight
	//         48             4,096   0.004 MiB  BF16   (2048,)          model.layers.N.post_attention_layernorm.weight
	//         48               256   0.000 MiB  BF16   (128,)           model.layers.N.self_attn.k_norm.weight
	//         48               256   0.000 MiB  BF16   (128,)           model.layers.N.self_attn.q_norm.weight
	//          1             4,096   0.004 MiB  BF16   (2048,)          model.norm.weight
	//
	// modal size: 3,145,728 B (3.000 MiB) shared by the most tensors (18,432 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 3,145,728 B (3.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"qwen3-coder-30b-a3b-instruct": 3145728,

	// === qwen2.5-coder-7b-instruct ===
	// repo:    Qwen/Qwen2.5-Coder-7B-Instruct @ c03e6d358207e414f1eca0bb1891e29f1db0e242
	// tensors: 339   total: 15,231,233,024 B (14.19 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         28       135,790,592  129.500 MiB  BF16   (3584, 18944)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         28       135,790,592  129.500 MiB  BF16   (18944, 3584)    model.layers.N.mlp.gate_proj.weight  <= modal (counted as 32 MiB cap)
	//         28       135,790,592  129.500 MiB  BF16   (18944, 3584)    model.layers.N.mlp.up_proj.weight  <= modal (counted as 32 MiB cap)
	//          1     1,089,994,752  1039.500 MiB  BF16   (152064, 3584)   lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1     1,089,994,752  1039.500 MiB  BF16   (152064, 3584)   model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         28        25,690,112  24.500 MiB  BF16   (3584, 3584)     model.layers.N.self_attn.o_proj.weight
	//         28        25,690,112  24.500 MiB  BF16   (3584, 3584)     model.layers.N.self_attn.q_proj.weight
	//         28         3,670,016   3.500 MiB  BF16   (512, 3584)      model.layers.N.self_attn.k_proj.weight
	//         28         3,670,016   3.500 MiB  BF16   (512, 3584)      model.layers.N.self_attn.v_proj.weight
	//         28             7,168   0.007 MiB  BF16   (3584,)          model.layers.N.input_layernorm.weight
	//         28             7,168   0.007 MiB  BF16   (3584,)          model.layers.N.post_attention_layernorm.weight
	//         28             7,168   0.007 MiB  BF16   (3584,)          model.layers.N.self_attn.q_proj.bias
	//         28             1,024   0.001 MiB  BF16   (512,)           model.layers.N.self_attn.k_proj.bias
	//         28             1,024   0.001 MiB  BF16   (512,)           model.layers.N.self_attn.v_proj.bias
	//          1             7,168   0.007 MiB  BF16   (3584,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (86 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"qwen2.5-coder-7b-instruct": 33554432,

	// === qwen2.5-coder-32b-instruct ===
	// repo:    Qwen/Qwen2.5-Coder-32B-Instruct @ 381fc969f78efac66bc87ff7ddeadb7e73c218a7
	// tensors: 771   total: 65,527,752,704 B (61.03 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         64       283,115,520  270.000 MiB  BF16   (5120, 27648)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         64       283,115,520  270.000 MiB  BF16   (27648, 5120)    model.layers.N.mlp.gate_proj.weight  <= modal (counted as 32 MiB cap)
	//         64       283,115,520  270.000 MiB  BF16   (27648, 5120)    model.layers.N.mlp.up_proj.weight  <= modal (counted as 32 MiB cap)
	//         64        52,428,800  50.000 MiB  BF16   (5120, 5120)     model.layers.N.self_attn.o_proj.weight  <= modal (counted as 32 MiB cap)
	//         64        52,428,800  50.000 MiB  BF16   (5120, 5120)     model.layers.N.self_attn.q_proj.weight  <= modal (counted as 32 MiB cap)
	//          1     1,557,135,360  1485.000 MiB  BF16   (152064, 5120)   lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1     1,557,135,360  1485.000 MiB  BF16   (152064, 5120)   model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         64        10,485,760  10.000 MiB  BF16   (1024, 5120)     model.layers.N.self_attn.k_proj.weight
	//         64        10,485,760  10.000 MiB  BF16   (1024, 5120)     model.layers.N.self_attn.v_proj.weight
	//         64            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.input_layernorm.weight
	//         64            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.post_attention_layernorm.weight
	//         64            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.self_attn.q_proj.bias
	//         64             2,048   0.002 MiB  BF16   (1024,)          model.layers.N.self_attn.k_proj.bias
	//         64             2,048   0.002 MiB  BF16   (1024,)          model.layers.N.self_attn.v_proj.bias
	//          1            10,240   0.010 MiB  BF16   (5120,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (322 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"qwen2.5-coder-32b-instruct": 33554432,

	// === gpt-oss-20b ===
	// repo:    openai/gpt-oss-20b @ db6852caddef0cf0c1f729034ed700c84eab376e
	// tensors: 459   total: 13,761,264,768 B (12.82 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         24       265,420,800  253.125 MiB  U8     (32, 5760, 90, 16) model.layers.N.mlp.experts.gate_up_proj_blocks
	//         24       132,710,400  126.562 MiB  U8     (32, 2880, 90, 16) model.layers.N.mlp.experts.down_proj_blocks
	//          1     1,158,266,880  1104.609 MiB  BF16   (201088, 2880)   lm_head.weight
	//          1     1,158,266,880  1104.609 MiB  BF16   (201088, 2880)   model.embed_tokens.weight
	//         24        23,592,960  22.500 MiB  BF16   (2880, 4096)     model.layers.N.self_attn.o_proj.weight
	//         24        23,592,960  22.500 MiB  BF16   (4096, 2880)     model.layers.N.self_attn.q_proj.weight
	//         24        16,588,800  15.820 MiB  U8     (32, 5760, 90)   model.layers.N.mlp.experts.gate_up_proj_scales
	//         24         8,294,400   7.910 MiB  U8     (32, 2880, 90)   model.layers.N.mlp.experts.down_proj_scales
	//         24         2,949,120   2.812 MiB  BF16   (512, 2880)      model.layers.N.self_attn.k_proj.weight
	//         24         2,949,120   2.812 MiB  BF16   (512, 2880)      model.layers.N.self_attn.v_proj.weight
	//         24           368,640   0.352 MiB  BF16   (32, 5760)       model.layers.N.mlp.experts.gate_up_proj_bias
	//         24           184,320   0.176 MiB  BF16   (32, 2880)       model.layers.N.mlp.experts.down_proj_bias
	//         24           184,320   0.176 MiB  BF16   (32, 2880)       model.layers.N.mlp.router.weight
	//         24             8,192   0.008 MiB  BF16   (4096,)          model.layers.N.self_attn.q_proj.bias
	//         24             5,760   0.005 MiB  BF16   (2880,)          model.layers.N.input_layernorm.weight  <= modal (most tensors at this size)
	//         24             5,760   0.005 MiB  BF16   (2880,)          model.layers.N.post_attention_layernorm.weight  <= modal (most tensors at this size)
	//         24             5,760   0.005 MiB  BF16   (2880,)          model.layers.N.self_attn.o_proj.bias  <= modal (most tensors at this size)
	//         24             1,024   0.001 MiB  BF16   (512,)           model.layers.N.self_attn.k_proj.bias
	//         24             1,024   0.001 MiB  BF16   (512,)           model.layers.N.self_attn.v_proj.bias
	//          1             5,760   0.005 MiB  BF16   (2880,)          model.norm.weight  <= modal (most tensors at this size)
	//         24               128   0.000 MiB  BF16   (64,)            model.layers.N.self_attn.sinks
	//         24                64   0.000 MiB  BF16   (32,)            model.layers.N.mlp.router.bias
	//
	// modal size: 5,760 B (0.005 MiB) shared by the most tensors (73 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 2,097,152 B (2.000 MiB) — raised to the 2 MiB minimum chunk floor.
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"gpt-oss-20b": 2097152,

	// === gpt-oss-120b ===
	// repo:    openai/gpt-oss-120b @ b5c939de8f754692c1647ca79fbf85e8c1e70f8a
	// tensors: 687   total: 65,248,815,744 B (60.77 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         36     1,061,683,200  1012.500 MiB  U8     (128, 5760, 90, 16) model.layers.N.mlp.experts.gate_up_proj_blocks  <= modal (counted as 32 MiB cap)
	//         36       530,841,600  506.250 MiB  U8     (128, 2880, 90, 16) model.layers.N.mlp.experts.down_proj_blocks  <= modal (counted as 32 MiB cap)
	//         36        66,355,200  63.281 MiB  U8     (128, 5760, 90)  model.layers.N.mlp.experts.gate_up_proj_scales  <= modal (counted as 32 MiB cap)
	//         36        33,177,600  31.641 MiB  U8     (128, 2880, 90)  model.layers.N.mlp.experts.down_proj_scales
	//          1     1,158,266,880  1104.609 MiB  BF16   (201088, 2880)   lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1     1,158,266,880  1104.609 MiB  BF16   (201088, 2880)   model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         36        23,592,960  22.500 MiB  BF16   (2880, 4096)     model.layers.N.self_attn.o_proj.weight
	//         36        23,592,960  22.500 MiB  BF16   (4096, 2880)     model.layers.N.self_attn.q_proj.weight
	//         36         2,949,120   2.812 MiB  BF16   (512, 2880)      model.layers.N.self_attn.k_proj.weight
	//         36         2,949,120   2.812 MiB  BF16   (512, 2880)      model.layers.N.self_attn.v_proj.weight
	//         36         1,474,560   1.406 MiB  BF16   (128, 5760)      model.layers.N.mlp.experts.gate_up_proj_bias
	//         36           737,280   0.703 MiB  BF16   (128, 2880)      model.layers.N.mlp.experts.down_proj_bias
	//         36           737,280   0.703 MiB  BF16   (128, 2880)      model.layers.N.mlp.router.weight
	//         36             8,192   0.008 MiB  BF16   (4096,)          model.layers.N.self_attn.q_proj.bias
	//         36             5,760   0.005 MiB  BF16   (2880,)          model.layers.N.input_layernorm.weight
	//         36             5,760   0.005 MiB  BF16   (2880,)          model.layers.N.post_attention_layernorm.weight
	//         36             5,760   0.005 MiB  BF16   (2880,)          model.layers.N.self_attn.o_proj.bias
	//         36             1,024   0.001 MiB  BF16   (512,)           model.layers.N.self_attn.k_proj.bias
	//         36             1,024   0.001 MiB  BF16   (512,)           model.layers.N.self_attn.v_proj.bias
	//         36               256   0.000 MiB  BF16   (128,)           model.layers.N.mlp.router.bias
	//          1             5,760   0.005 MiB  BF16   (2880,)          model.norm.weight
	//         36               128   0.000 MiB  BF16   (64,)            model.layers.N.self_attn.sinks
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (110 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"gpt-oss-120b": 33554432,

	// === deepseek-r1-0528 ===
	// repo:    deepseek-ai/DeepSeek-R1-0528 @ 4236a6af538feda4548eca9ab308586007567f52
	// tensors: 91,991   total: 688,574,839,360 B (641.29 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//      15104        14,680,064  14.000 MiB  F8_E4M3 (7168, 2048)     model.layers.N.mlp.experts.N.down_proj.weight  <= modal (most tensors at this size)
	//      15104        14,680,064  14.000 MiB  F8_E4M3 (2048, 7168)     model.layers.N.mlp.experts.N.gate_proj.weight  <= modal (most tensors at this size)
	//      15104        14,680,064  14.000 MiB  F8_E4M3 (2048, 7168)     model.layers.N.mlp.experts.N.up_proj.weight  <= modal (most tensors at this size)
	//         62       117,440,512  112.000 MiB  F8_E4M3 (7168, 16384)    model.layers.N.self_attn.o_proj.weight
	//         62        37,748,736  36.000 MiB  F8_E4M3 (24576, 1536)    model.layers.N.self_attn.q_b_proj.weight
	//          1     1,853,358,080  1767.500 MiB  BF16   (129280, 7168)   lm_head.weight
	//          1     1,853,358,080  1767.500 MiB  BF16   (129280, 7168)   model.embed_tokens.weight
	//          1     1,853,358,080  1767.500 MiB  BF16   (129280, 7168)   model.layers.N.embed_tokens.weight
	//          1     1,853,358,080  1767.500 MiB  BF16   (129280, 7168)   model.layers.N.shared_head.head.weight
	//         62        16,777,216  16.000 MiB  F8_E4M3 (32768, 512)     model.layers.N.self_attn.kv_b_proj.weight
	//         59        14,680,064  14.000 MiB  F8_E4M3 (7168, 2048)     model.layers.N.mlp.shared_experts.down_proj.weight  <= modal (most tensors at this size)
	//         59        14,680,064  14.000 MiB  F8_E4M3 (2048, 7168)     model.layers.N.mlp.shared_experts.gate_proj.weight  <= modal (most tensors at this size)
	//         59        14,680,064  14.000 MiB  F8_E4M3 (2048, 7168)     model.layers.N.mlp.shared_experts.up_proj.weight  <= modal (most tensors at this size)
	//         62        11,010,048  10.500 MiB  F8_E4M3 (1536, 7168)     model.layers.N.self_attn.q_a_proj.weight
	//          3       132,120,576  126.000 MiB  F8_E4M3 (7168, 18432)    model.layers.N.mlp.down_proj.weight
	//          3       132,120,576  126.000 MiB  F8_E4M3 (18432, 7168)    model.layers.N.mlp.gate_proj.weight
	//          3       132,120,576  126.000 MiB  F8_E4M3 (18432, 7168)    model.layers.N.mlp.up_proj.weight
	//         62         4,128,768   3.938 MiB  F8_E4M3 (576, 7168)      model.layers.N.self_attn.kv_a_proj_with_mqa.weight
	//         59         3,670,016   3.500 MiB  BF16   (256, 7168)      model.layers.N.mlp.gate.weight
	//          1       205,520,896  196.000 MiB  BF16   (7168, 14336)    model.layers.N.eh_proj.weight
	//      15104             3,584   0.003 MiB  F32    (56, 16)         model.layers.N.mlp.experts.N.down_proj.weight_scale_inv
	//      15104             3,584   0.003 MiB  F32    (16, 56)         model.layers.N.mlp.experts.N.gate_proj.weight_scale_inv
	//      15104             3,584   0.003 MiB  F32    (16, 56)         model.layers.N.mlp.experts.N.up_proj.weight_scale_inv
	//         62            28,672   0.027 MiB  F32    (56, 128)        model.layers.N.self_attn.o_proj.weight_scale_inv
	//         62            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.input_layernorm.weight
	//         62            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.post_attention_layernorm.weight
	//         62             9,216   0.009 MiB  F32    (192, 12)        model.layers.N.self_attn.q_b_proj.weight_scale_inv
	//         62             4,096   0.004 MiB  F32    (256, 4)         model.layers.N.self_attn.kv_b_proj.weight_scale_inv
	//         59             3,584   0.003 MiB  F32    (56, 16)         model.layers.N.mlp.shared_experts.down_proj.weight_scale_inv
	//         59             3,584   0.003 MiB  F32    (16, 56)         model.layers.N.mlp.shared_experts.gate_proj.weight_scale_inv
	//         59             3,584   0.003 MiB  F32    (16, 56)         model.layers.N.mlp.shared_experts.up_proj.weight_scale_inv
	//         62             3,072   0.003 MiB  BF16   (1536,)          model.layers.N.self_attn.q_a_layernorm.weight
	//         62             2,688   0.003 MiB  F32    (12, 56)         model.layers.N.self_attn.q_a_proj.weight_scale_inv
	//          3            32,256   0.031 MiB  F32    (56, 144)        model.layers.N.mlp.down_proj.weight_scale_inv
	//          3            32,256   0.031 MiB  F32    (144, 56)        model.layers.N.mlp.gate_proj.weight_scale_inv
	//          3            32,256   0.031 MiB  F32    (144, 56)        model.layers.N.mlp.up_proj.weight_scale_inv
	//         62             1,120   0.001 MiB  F32    (5, 56)          model.layers.N.self_attn.kv_a_proj_with_mqa.weight_scale_inv
	//         62             1,024   0.001 MiB  BF16   (512,)           model.layers.N.self_attn.kv_a_layernorm.weight
	//         59             1,024   0.001 MiB  F32    (256,)           model.layers.N.mlp.gate.e_score_correction_bias
	//          1            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.enorm.weight
	//          1            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.hnorm.weight
	//          1            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.shared_head.norm.weight
	//          1            14,336   0.014 MiB  BF16   (7168,)          model.norm.weight
	//
	// modal size: 14,680,064 B (14.000 MiB) shared by the most tensors (45,489 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 14,680,064 B (14.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"deepseek-r1-0528": 14680064,

	// === deepseek-v3-0324 ===
	// repo:    deepseek-ai/DeepSeek-V3-0324 @ e9b33add76883f293d6bf61f6bd89b497e80e335
	// tensors: 91,991   total: 688,574,839,360 B (641.29 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//      15104        14,680,064  14.000 MiB  F8_E4M3 (7168, 2048)     model.layers.N.mlp.experts.N.down_proj.weight  <= modal (most tensors at this size)
	//      15104        14,680,064  14.000 MiB  F8_E4M3 (2048, 7168)     model.layers.N.mlp.experts.N.gate_proj.weight  <= modal (most tensors at this size)
	//      15104        14,680,064  14.000 MiB  F8_E4M3 (2048, 7168)     model.layers.N.mlp.experts.N.up_proj.weight  <= modal (most tensors at this size)
	//         62       117,440,512  112.000 MiB  F8_E4M3 (7168, 16384)    model.layers.N.self_attn.o_proj.weight
	//         62        37,748,736  36.000 MiB  F8_E4M3 (24576, 1536)    model.layers.N.self_attn.q_b_proj.weight
	//          1     1,853,358,080  1767.500 MiB  BF16   (129280, 7168)   lm_head.weight
	//          1     1,853,358,080  1767.500 MiB  BF16   (129280, 7168)   model.embed_tokens.weight
	//          1     1,853,358,080  1767.500 MiB  BF16   (129280, 7168)   model.layers.N.embed_tokens.weight
	//          1     1,853,358,080  1767.500 MiB  BF16   (129280, 7168)   model.layers.N.shared_head.head.weight
	//         62        16,777,216  16.000 MiB  F8_E4M3 (32768, 512)     model.layers.N.self_attn.kv_b_proj.weight
	//         59        14,680,064  14.000 MiB  F8_E4M3 (7168, 2048)     model.layers.N.mlp.shared_experts.down_proj.weight  <= modal (most tensors at this size)
	//         59        14,680,064  14.000 MiB  F8_E4M3 (2048, 7168)     model.layers.N.mlp.shared_experts.gate_proj.weight  <= modal (most tensors at this size)
	//         59        14,680,064  14.000 MiB  F8_E4M3 (2048, 7168)     model.layers.N.mlp.shared_experts.up_proj.weight  <= modal (most tensors at this size)
	//         62        11,010,048  10.500 MiB  F8_E4M3 (1536, 7168)     model.layers.N.self_attn.q_a_proj.weight
	//          3       132,120,576  126.000 MiB  F8_E4M3 (7168, 18432)    model.layers.N.mlp.down_proj.weight
	//          3       132,120,576  126.000 MiB  F8_E4M3 (18432, 7168)    model.layers.N.mlp.gate_proj.weight
	//          3       132,120,576  126.000 MiB  F8_E4M3 (18432, 7168)    model.layers.N.mlp.up_proj.weight
	//         62         4,128,768   3.938 MiB  F8_E4M3 (576, 7168)      model.layers.N.self_attn.kv_a_proj_with_mqa.weight
	//         59         3,670,016   3.500 MiB  BF16   (256, 7168)      model.layers.N.mlp.gate.weight
	//          1       205,520,896  196.000 MiB  BF16   (7168, 14336)    model.layers.N.eh_proj.weight
	//      15104             3,584   0.003 MiB  F32    (56, 16)         model.layers.N.mlp.experts.N.down_proj.weight_scale_inv
	//      15104             3,584   0.003 MiB  F32    (16, 56)         model.layers.N.mlp.experts.N.gate_proj.weight_scale_inv
	//      15104             3,584   0.003 MiB  F32    (16, 56)         model.layers.N.mlp.experts.N.up_proj.weight_scale_inv
	//         62            28,672   0.027 MiB  F32    (56, 128)        model.layers.N.self_attn.o_proj.weight_scale_inv
	//         62            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.input_layernorm.weight
	//         62            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.post_attention_layernorm.weight
	//         62             9,216   0.009 MiB  F32    (192, 12)        model.layers.N.self_attn.q_b_proj.weight_scale_inv
	//         62             4,096   0.004 MiB  F32    (256, 4)         model.layers.N.self_attn.kv_b_proj.weight_scale_inv
	//         59             3,584   0.003 MiB  F32    (56, 16)         model.layers.N.mlp.shared_experts.down_proj.weight_scale_inv
	//         59             3,584   0.003 MiB  F32    (16, 56)         model.layers.N.mlp.shared_experts.gate_proj.weight_scale_inv
	//         59             3,584   0.003 MiB  F32    (16, 56)         model.layers.N.mlp.shared_experts.up_proj.weight_scale_inv
	//         62             3,072   0.003 MiB  BF16   (1536,)          model.layers.N.self_attn.q_a_layernorm.weight
	//         62             2,688   0.003 MiB  F32    (12, 56)         model.layers.N.self_attn.q_a_proj.weight_scale_inv
	//          3            32,256   0.031 MiB  F32    (56, 144)        model.layers.N.mlp.down_proj.weight_scale_inv
	//          3            32,256   0.031 MiB  F32    (144, 56)        model.layers.N.mlp.gate_proj.weight_scale_inv
	//          3            32,256   0.031 MiB  F32    (144, 56)        model.layers.N.mlp.up_proj.weight_scale_inv
	//         62             1,120   0.001 MiB  F32    (5, 56)          model.layers.N.self_attn.kv_a_proj_with_mqa.weight_scale_inv
	//         62             1,024   0.001 MiB  BF16   (512,)           model.layers.N.self_attn.kv_a_layernorm.weight
	//         59             1,024   0.001 MiB  F32    (256,)           model.layers.N.mlp.gate.e_score_correction_bias
	//          1            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.enorm.weight
	//          1            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.hnorm.weight
	//          1            14,336   0.014 MiB  BF16   (7168,)          model.layers.N.shared_head.norm.weight
	//          1            14,336   0.014 MiB  BF16   (7168,)          model.norm.weight
	//
	// modal size: 14,680,064 B (14.000 MiB) shared by the most tensors (45,489 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 14,680,064 B (14.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"deepseek-v3-0324": 14680064,

	// === phi-2 ===
	// repo:    microsoft/phi-2 @ ef382358ec9e382308935a992d908de099b64c23
	// tensors: 453   total: 5,559,367,680 B (5.18 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32        52,428,800  50.000 MiB  F16    (10240, 2560)    model.layers.N.mlp.fc1.weight
	//         32        52,428,800  50.000 MiB  F16    (2560, 10240)    model.layers.N.mlp.fc2.weight
	//         32        13,107,200  12.500 MiB  F16    (2560, 2560)     model.layers.N.self_attn.dense.weight
	//         32        13,107,200  12.500 MiB  F16    (2560, 2560)     model.layers.N.self_attn.k_proj.weight
	//         32        13,107,200  12.500 MiB  F16    (2560, 2560)     model.layers.N.self_attn.q_proj.weight
	//         32        13,107,200  12.500 MiB  F16    (2560, 2560)     model.layers.N.self_attn.v_proj.weight
	//          1       262,144,000  250.000 MiB  F16    (51200, 2560)    lm_head.weight
	//          1       262,144,000  250.000 MiB  F16    (51200, 2560)    model.embed_tokens.weight
	//         32            20,480   0.020 MiB  F16    (10240,)         model.layers.N.mlp.fc1.bias
	//         32             5,120   0.005 MiB  F16    (2560,)          model.layers.N.input_layernorm.bias  <= modal (most tensors at this size)
	//         32             5,120   0.005 MiB  F16    (2560,)          model.layers.N.input_layernorm.weight  <= modal (most tensors at this size)
	//         32             5,120   0.005 MiB  F16    (2560,)          model.layers.N.mlp.fc2.bias  <= modal (most tensors at this size)
	//         32             5,120   0.005 MiB  F16    (2560,)          model.layers.N.self_attn.dense.bias  <= modal (most tensors at this size)
	//         32             5,120   0.005 MiB  F16    (2560,)          model.layers.N.self_attn.k_proj.bias  <= modal (most tensors at this size)
	//         32             5,120   0.005 MiB  F16    (2560,)          model.layers.N.self_attn.q_proj.bias  <= modal (most tensors at this size)
	//         32             5,120   0.005 MiB  F16    (2560,)          model.layers.N.self_attn.v_proj.bias  <= modal (most tensors at this size)
	//          1           102,400   0.098 MiB  F16    (51200,)         lm_head.bias
	//          1             5,120   0.005 MiB  F16    (2560,)          model.final_layernorm.bias  <= modal (most tensors at this size)
	//          1             5,120   0.005 MiB  F16    (2560,)          model.final_layernorm.weight  <= modal (most tensors at this size)
	//
	// modal size: 5,120 B (0.005 MiB) shared by the most tensors (226 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 2,097,152 B (2.000 MiB) — raised to the 2 MiB minimum chunk floor.
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"phi-2": 2097152,

	// === phi-3-mini-4k-instruct ===
	// repo:    microsoft/Phi-3-mini-4k-instruct @ 0a67737cc96d2554230f90338b163bc6380a2a85
	// tensors: 195   total: 7,642,159,104 B (7.12 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       100,663,296  96.000 MiB  BF16   (16384, 3072)    model.layers.N.mlp.gate_up_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        56,623,104  54.000 MiB  BF16   (9216, 3072)     model.layers.N.self_attn.qkv_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        50,331,648  48.000 MiB  BF16   (3072, 8192)     model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        18,874,368  18.000 MiB  BF16   (3072, 3072)     model.layers.N.self_attn.o_proj.weight
	//          1       197,001,216  187.875 MiB  BF16   (32064, 3072)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       197,001,216  187.875 MiB  BF16   (32064, 3072)    model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         32             6,144   0.006 MiB  BF16   (3072,)          model.layers.N.input_layernorm.weight
	//         32             6,144   0.006 MiB  BF16   (3072,)          model.layers.N.post_attention_layernorm.weight
	//          1             6,144   0.006 MiB  BF16   (3072,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (98 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"phi-3-mini-4k-instruct": 33554432,

	// === phi-3-mini-128k-instruct ===
	// repo:    microsoft/Phi-3-mini-128k-instruct @ 072cb7562cb8c4adf682a8e186aaafa49469eb5d
	// tensors: 195   total: 7,642,159,104 B (7.12 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       100,663,296  96.000 MiB  BF16   (16384, 3072)    model.layers.N.mlp.gate_up_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        56,623,104  54.000 MiB  BF16   (9216, 3072)     model.layers.N.self_attn.qkv_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        50,331,648  48.000 MiB  BF16   (3072, 8192)     model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        18,874,368  18.000 MiB  BF16   (3072, 3072)     model.layers.N.self_attn.o_proj.weight
	//          1       197,001,216  187.875 MiB  BF16   (32064, 3072)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       197,001,216  187.875 MiB  BF16   (32064, 3072)    model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         32             6,144   0.006 MiB  BF16   (3072,)          model.layers.N.input_layernorm.weight
	//         32             6,144   0.006 MiB  BF16   (3072,)          model.layers.N.post_attention_layernorm.weight
	//          1             6,144   0.006 MiB  BF16   (3072,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (98 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"phi-3-mini-128k-instruct": 33554432,

	// === phi-3-medium-4k-instruct ===
	// repo:    microsoft/Phi-3-medium-4k-instruct @ b64223aaea6fbf273c0c8cd0801d5e732dce8897
	// tensors: 243   total: 27,920,476,160 B (26.00 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         40       367,001,600  350.000 MiB  BF16   (35840, 5120)    model.layers.N.mlp.gate_up_proj.weight  <= modal (counted as 32 MiB cap)
	//         40       183,500,800  175.000 MiB  BF16   (5120, 17920)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         40        78,643,200  75.000 MiB  BF16   (7680, 5120)     model.layers.N.self_attn.qkv_proj.weight  <= modal (counted as 32 MiB cap)
	//         40        52,428,800  50.000 MiB  BF16   (5120, 5120)     model.layers.N.self_attn.o_proj.weight  <= modal (counted as 32 MiB cap)
	//          1       328,335,360  313.125 MiB  BF16   (32064, 5120)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       328,335,360  313.125 MiB  BF16   (32064, 5120)    model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         40            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.input_layernorm.weight
	//         40            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.post_attention_layernorm.weight
	//          1            10,240   0.010 MiB  BF16   (5120,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (162 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"phi-3-medium-4k-instruct": 33554432,

	// === phi-3-medium-128k-instruct ===
	// repo:    microsoft/Phi-3-medium-128k-instruct @ fa7d2aa4f5ea69b2e36b20d050cdae79c9bfbb3f
	// tensors: 243   total: 27,920,476,160 B (26.00 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         40       367,001,600  350.000 MiB  BF16   (35840, 5120)    model.layers.N.mlp.gate_up_proj.weight  <= modal (counted as 32 MiB cap)
	//         40       183,500,800  175.000 MiB  BF16   (5120, 17920)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         40        78,643,200  75.000 MiB  BF16   (7680, 5120)     model.layers.N.self_attn.qkv_proj.weight  <= modal (counted as 32 MiB cap)
	//         40        52,428,800  50.000 MiB  BF16   (5120, 5120)     model.layers.N.self_attn.o_proj.weight  <= modal (counted as 32 MiB cap)
	//          1       328,335,360  313.125 MiB  BF16   (32064, 5120)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       328,335,360  313.125 MiB  BF16   (32064, 5120)    model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         40            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.input_layernorm.weight
	//         40            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.post_attention_layernorm.weight
	//          1            10,240   0.010 MiB  BF16   (5120,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (162 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"phi-3-medium-128k-instruct": 33554432,

	// === phi-3.5-mini-instruct ===
	// repo:    microsoft/Phi-3.5-mini-instruct @ 3145e03a9fd4cdd7cd953c34d9bbf7ad606122ca
	// tensors: 195   total: 7,642,159,104 B (7.12 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       100,663,296  96.000 MiB  BF16   (16384, 3072)    model.layers.N.mlp.gate_up_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        56,623,104  54.000 MiB  BF16   (9216, 3072)     model.layers.N.self_attn.qkv_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        50,331,648  48.000 MiB  BF16   (3072, 8192)     model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        18,874,368  18.000 MiB  BF16   (3072, 3072)     model.layers.N.self_attn.o_proj.weight
	//          1       197,001,216  187.875 MiB  BF16   (32064, 3072)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       197,001,216  187.875 MiB  BF16   (32064, 3072)    model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         32             6,144   0.006 MiB  BF16   (3072,)          model.layers.N.input_layernorm.weight
	//         32             6,144   0.006 MiB  BF16   (3072,)          model.layers.N.post_attention_layernorm.weight
	//          1             6,144   0.006 MiB  BF16   (3072,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (98 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"phi-3.5-mini-instruct": 33554432,

	// === phi-4-mini-instruct ===
	// repo:    microsoft/Phi-4-mini-instruct @ c0fb9e74abda11b496b7907a9c6c9009a7a0488f
	// tensors: 194   total: 7,672,043,520 B (7.15 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       100,663,296  96.000 MiB  BF16   (16384, 3072)    model.layers.N.mlp.gate_up_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        50,331,648  48.000 MiB  BF16   (3072, 8192)     model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//          1     1,229,193,216  1172.250 MiB  BF16   (200064, 3072)   model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         32        31,457,280  30.000 MiB  BF16   (5120, 3072)     model.layers.N.self_attn.qkv_proj.weight
	//         32        18,874,368  18.000 MiB  BF16   (3072, 3072)     model.layers.N.self_attn.o_proj.weight
	//         32             6,144   0.006 MiB  BF16   (3072,)          model.layers.N.input_layernorm.weight
	//         32             6,144   0.006 MiB  BF16   (3072,)          model.layers.N.post_attention_layernorm.weight
	//          1             6,144   0.006 MiB  BF16   (3072,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (65 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"phi-4-mini-instruct": 33554432,

	// === phi-4 ===
	// repo:    microsoft/phi-4 @ 187ef0342fff0eb3333be9f00389385e95ef0b61
	// tensors: 243   total: 29,319,014,400 B (27.31 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         40       367,001,600  350.000 MiB  BF16   (35840, 5120)    model.layers.N.mlp.gate_up_proj.weight  <= modal (counted as 32 MiB cap)
	//         40       183,500,800  175.000 MiB  BF16   (5120, 17920)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         40        78,643,200  75.000 MiB  BF16   (7680, 5120)     model.layers.N.self_attn.qkv_proj.weight  <= modal (counted as 32 MiB cap)
	//         40        52,428,800  50.000 MiB  BF16   (5120, 5120)     model.layers.N.self_attn.o_proj.weight  <= modal (counted as 32 MiB cap)
	//          1     1,027,604,480  980.000 MiB  BF16   (100352, 5120)   lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1     1,027,604,480  980.000 MiB  BF16   (100352, 5120)   model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         40            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.input_layernorm.weight
	//         40            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.post_attention_layernorm.weight
	//          1            10,240   0.010 MiB  BF16   (5120,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (162 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"phi-4": 33554432,

	// === deepseek-r1-distill-qwen-14b ===
	// repo:    deepseek-ai/DeepSeek-R1-Distill-Qwen-14B @ 1df8507178afcc1bef68cd8c393f61a886323761
	// tensors: 579   total: 29,540,067,328 B (27.51 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         48       141,557,760  135.000 MiB  BF16   (5120, 13824)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         48       141,557,760  135.000 MiB  BF16   (13824, 5120)    model.layers.N.mlp.gate_proj.weight  <= modal (counted as 32 MiB cap)
	//         48       141,557,760  135.000 MiB  BF16   (13824, 5120)    model.layers.N.mlp.up_proj.weight  <= modal (counted as 32 MiB cap)
	//         48        52,428,800  50.000 MiB  BF16   (5120, 5120)     model.layers.N.self_attn.o_proj.weight  <= modal (counted as 32 MiB cap)
	//         48        52,428,800  50.000 MiB  BF16   (5120, 5120)     model.layers.N.self_attn.q_proj.weight  <= modal (counted as 32 MiB cap)
	//          1     1,557,135,360  1485.000 MiB  BF16   (152064, 5120)   lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1     1,557,135,360  1485.000 MiB  BF16   (152064, 5120)   model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         48        10,485,760  10.000 MiB  BF16   (1024, 5120)     model.layers.N.self_attn.k_proj.weight
	//         48        10,485,760  10.000 MiB  BF16   (1024, 5120)     model.layers.N.self_attn.v_proj.weight
	//         48            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.input_layernorm.weight
	//         48            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.post_attention_layernorm.weight
	//         48            10,240   0.010 MiB  BF16   (5120,)          model.layers.N.self_attn.q_proj.bias
	//         48             2,048   0.002 MiB  BF16   (1024,)          model.layers.N.self_attn.k_proj.bias
	//         48             2,048   0.002 MiB  BF16   (1024,)          model.layers.N.self_attn.v_proj.bias
	//          1            10,240   0.010 MiB  BF16   (5120,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (242 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"deepseek-r1-distill-qwen-14b": 33554432,

	// === deepseek-r1-distill-llama-8b ===
	// repo:    deepseek-ai/DeepSeek-R1-Distill-Llama-8B @ 6a6f4aa4197940add57724a7707d069478df56b1
	// tensors: 291   total: 16,060,522,496 B (14.96 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       117,440,512  112.000 MiB  BF16   (4096, 14336)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         32       117,440,512  112.000 MiB  BF16   (14336, 4096)    model.layers.N.mlp.gate_proj.weight  <= modal (counted as 32 MiB cap)
	//         32       117,440,512  112.000 MiB  BF16   (14336, 4096)    model.layers.N.mlp.up_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        33,554,432  32.000 MiB  BF16   (4096, 4096)     model.layers.N.self_attn.o_proj.weight  <= modal (most tensors at this size)
	//         32        33,554,432  32.000 MiB  BF16   (4096, 4096)     model.layers.N.self_attn.q_proj.weight  <= modal (most tensors at this size)
	//          1     1,050,673,152  1002.000 MiB  BF16   (128256, 4096)   lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1     1,050,673,152  1002.000 MiB  BF16   (128256, 4096)   model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         32         8,388,608   8.000 MiB  BF16   (1024, 4096)     model.layers.N.self_attn.k_proj.weight
	//         32         8,388,608   8.000 MiB  BF16   (1024, 4096)     model.layers.N.self_attn.v_proj.weight
	//         32             8,192   0.008 MiB  BF16   (4096,)          model.layers.N.input_layernorm.weight
	//         32             8,192   0.008 MiB  BF16   (4096,)          model.layers.N.post_attention_layernorm.weight
	//          1             8,192   0.008 MiB  BF16   (4096,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (162 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"deepseek-r1-distill-llama-8b": 33554432,

	// === mistral-7b ===
	// repo:    mistralai/Mistral-7B-v0.3 @ d8cadc02ac76bd617a919d50b092e59d2d110aff
	// tensors: 291   total: 14,496,047,104 B (13.50 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       117,440,512  112.000 MiB  BF16   (4096, 14336)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         32       117,440,512  112.000 MiB  BF16   (14336, 4096)    model.layers.N.mlp.gate_proj.weight  <= modal (counted as 32 MiB cap)
	//         32       117,440,512  112.000 MiB  BF16   (14336, 4096)    model.layers.N.mlp.up_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        33,554,432  32.000 MiB  BF16   (4096, 4096)     model.layers.N.self_attn.o_proj.weight  <= modal (most tensors at this size)
	//         32        33,554,432  32.000 MiB  BF16   (4096, 4096)     model.layers.N.self_attn.q_proj.weight  <= modal (most tensors at this size)
	//          1       268,435,456  256.000 MiB  BF16   (32768, 4096)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       268,435,456  256.000 MiB  BF16   (32768, 4096)    model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         32         8,388,608   8.000 MiB  BF16   (1024, 4096)     model.layers.N.self_attn.k_proj.weight
	//         32         8,388,608   8.000 MiB  BF16   (1024, 4096)     model.layers.N.self_attn.v_proj.weight
	//         32             8,192   0.008 MiB  BF16   (4096,)          model.layers.N.input_layernorm.weight
	//         32             8,192   0.008 MiB  BF16   (4096,)          model.layers.N.post_attention_layernorm.weight
	//          1             8,192   0.008 MiB  BF16   (4096,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (162 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"mistral-7b-v0.3": 33554432,
	"mistral-7b":      33554432, // alias (preset name)

	// === mistral-7b-instruct ===
	// repo:    mistralai/Mistral-7B-Instruct-v0.3 @ e0bc86c23ce5aae1db576c8cca6f06f1f73af2db
	// tensors: 291   total: 14,496,047,104 B (13.50 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       117,440,512  112.000 MiB  BF16   (4096, 14336)    model.layers.N.mlp.down_proj.weight  <= modal (counted as 32 MiB cap)
	//         32       117,440,512  112.000 MiB  BF16   (14336, 4096)    model.layers.N.mlp.gate_proj.weight  <= modal (counted as 32 MiB cap)
	//         32       117,440,512  112.000 MiB  BF16   (14336, 4096)    model.layers.N.mlp.up_proj.weight  <= modal (counted as 32 MiB cap)
	//         32        33,554,432  32.000 MiB  BF16   (4096, 4096)     model.layers.N.self_attn.o_proj.weight  <= modal (most tensors at this size)
	//         32        33,554,432  32.000 MiB  BF16   (4096, 4096)     model.layers.N.self_attn.q_proj.weight  <= modal (most tensors at this size)
	//          1       268,435,456  256.000 MiB  BF16   (32768, 4096)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       268,435,456  256.000 MiB  BF16   (32768, 4096)    model.embed_tokens.weight  <= modal (counted as 32 MiB cap)
	//         32         8,388,608   8.000 MiB  BF16   (1024, 4096)     model.layers.N.self_attn.k_proj.weight
	//         32         8,388,608   8.000 MiB  BF16   (1024, 4096)     model.layers.N.self_attn.v_proj.weight
	//         32             8,192   0.008 MiB  BF16   (4096,)          model.layers.N.input_layernorm.weight
	//         32             8,192   0.008 MiB  BF16   (4096,)          model.layers.N.post_attention_layernorm.weight
	//          1             8,192   0.008 MiB  BF16   (4096,)          model.norm.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (162 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"mistral-7b-instruct-v0.3": 33554432,
	"mistral-7b-instruct":      33554432, // alias (preset name)

	// === ministral-3-3b-instruct ===
	// repo:    mistralai/Ministral-3-3B-Instruct-2512 @ 83e15808ff6a115f18ff8e68123db3ab35035714
	// tensors: 822   total: 4,671,990,488 B (4.35 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//          1       805,306,368  768.000 MiB  BF16   (131072, 3072)   language_model.model.embed_tokens.weight
	//         26        28,311,552  27.000 MiB  F8_E4M3 (3072, 9216)     language_model.model.layers.N.mlp.down_proj.weight
	//         26        28,311,552  27.000 MiB  F8_E4M3 (9216, 3072)     language_model.model.layers.N.mlp.gate_proj.weight
	//         26        28,311,552  27.000 MiB  F8_E4M3 (9216, 3072)     language_model.model.layers.N.mlp.up_proj.weight
	//         26        12,582,912  12.000 MiB  F8_E4M3 (3072, 4096)     language_model.model.layers.N.self_attn.o_proj.weight
	//         26        12,582,912  12.000 MiB  F8_E4M3 (4096, 3072)     language_model.model.layers.N.self_attn.q_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (1024, 4096)     vision_tower.transformer.layers.N.feed_forward.down_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (4096, 1024)     vision_tower.transformer.layers.N.feed_forward.gate_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (4096, 1024)     vision_tower.transformer.layers.N.feed_forward.up_proj.weight
	//         26         3,145,728   3.000 MiB  F8_E4M3 (1024, 3072)     language_model.model.layers.N.self_attn.k_proj.weight
	//         26         3,145,728   3.000 MiB  F8_E4M3 (1024, 3072)     language_model.model.layers.N.self_attn.v_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.k_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.o_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.q_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.v_proj.weight
	//          1        18,874,368  18.000 MiB  BF16   (3072, 3072)     multi_modal_projector.linear_2.weight
	//          1         8,388,608   8.000 MiB  BF16   (1024, 4096)     multi_modal_projector.patch_merger.merging_layer.weight
	//          1         6,291,456   6.000 MiB  BF16   (3072, 1024)     multi_modal_projector.linear_1.weight
	//          1         1,204,224   1.148 MiB  BF16   (1024, 3, 14, 14) vision_tower.patch_conv.weight
	//         26             6,144   0.006 MiB  BF16   (3072,)          language_model.model.layers.N.input_layernorm.weight
	//         26             6,144   0.006 MiB  BF16   (3072,)          language_model.model.layers.N.post_attention_layernorm.weight
	//         24             2,048   0.002 MiB  BF16   (1024,)          vision_tower.transformer.layers.N.attention_norm.weight
	//         24             2,048   0.002 MiB  BF16   (1024,)          vision_tower.transformer.layers.N.ffn_norm.weight
	//          1             6,144   0.006 MiB  BF16   (3072,)          language_model.model.norm.weight
	//          1             2,048   0.002 MiB  BF16   (1024,)          multi_modal_projector.norm.weight
	//          1             2,048   0.002 MiB  BF16   (1024,)          vision_tower.ln_pre.weight
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.down_proj.activation_scale  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.down_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.gate_proj.activation_scale  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.gate_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.up_proj.activation_scale  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.up_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.k_proj.activation_scale  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.k_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.o_proj.activation_scale  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.o_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.q_proj.activation_scale  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.q_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.v_proj.activation_scale  <= modal (most tensors at this size)
	//         26                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.v_proj.weight_scale_inv  <= modal (most tensors at this size)
	//
	// modal size: 2 B (0.000 MiB) shared by the most tensors (364 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 2,097,152 B (2.000 MiB) — raised to the 2 MiB minimum chunk floor.
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"ministral-3-3b-instruct-2512": 2097152,
	"ministral-3-3b-instruct":      2097152, // alias (preset name)

	// === ministral-3-8b-instruct ===
	// repo:    mistralai/Ministral-3-8B-Instruct-2512 @ df904c183734f8760042c708d3629a4ed68b103a
	// tensors: 1,007   total: 10,420,523,960 B (9.70 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         34        58,720,256  56.000 MiB  F8_E4M3 (4096, 14336)    language_model.model.layers.N.mlp.down_proj.weight
	//         34        58,720,256  56.000 MiB  F8_E4M3 (14336, 4096)    language_model.model.layers.N.mlp.gate_proj.weight
	//         34        58,720,256  56.000 MiB  F8_E4M3 (14336, 4096)    language_model.model.layers.N.mlp.up_proj.weight
	//          1     1,073,741,824  1024.000 MiB  BF16   (131072, 4096)   language_model.lm_head.weight
	//          1     1,073,741,824  1024.000 MiB  BF16   (131072, 4096)   language_model.model.embed_tokens.weight
	//         34        16,777,216  16.000 MiB  F8_E4M3 (4096, 4096)     language_model.model.layers.N.self_attn.o_proj.weight
	//         34        16,777,216  16.000 MiB  F8_E4M3 (4096, 4096)     language_model.model.layers.N.self_attn.q_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (1024, 4096)     vision_tower.transformer.layers.N.feed_forward.down_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (4096, 1024)     vision_tower.transformer.layers.N.feed_forward.gate_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (4096, 1024)     vision_tower.transformer.layers.N.feed_forward.up_proj.weight
	//         34         4,194,304   4.000 MiB  F8_E4M3 (1024, 4096)     language_model.model.layers.N.self_attn.k_proj.weight
	//         34         4,194,304   4.000 MiB  F8_E4M3 (1024, 4096)     language_model.model.layers.N.self_attn.v_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.k_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.o_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.q_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.v_proj.weight
	//          1        33,554,432  32.000 MiB  BF16   (4096, 4096)     multi_modal_projector.linear_2.weight
	//          1         8,388,608   8.000 MiB  BF16   (4096, 1024)     multi_modal_projector.linear_1.weight
	//          1         8,388,608   8.000 MiB  BF16   (1024, 4096)     multi_modal_projector.patch_merger.merging_layer.weight
	//          1         1,204,224   1.148 MiB  BF16   (1024, 3, 14, 14) vision_tower.patch_conv.weight
	//         34             8,192   0.008 MiB  BF16   (4096,)          language_model.model.layers.N.input_layernorm.weight
	//         34             8,192   0.008 MiB  BF16   (4096,)          language_model.model.layers.N.post_attention_layernorm.weight
	//         24             2,048   0.002 MiB  BF16   (1024,)          vision_tower.transformer.layers.N.attention_norm.weight
	//         24             2,048   0.002 MiB  BF16   (1024,)          vision_tower.transformer.layers.N.ffn_norm.weight
	//          1             8,192   0.008 MiB  BF16   (4096,)          language_model.model.norm.weight
	//          1             2,048   0.002 MiB  BF16   (1024,)          multi_modal_projector.norm.weight
	//          1             2,048   0.002 MiB  BF16   (1024,)          vision_tower.ln_pre.weight
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.down_proj.activation_scale  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.down_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.gate_proj.activation_scale  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.gate_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.up_proj.activation_scale  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.up_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.k_proj.activation_scale  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.k_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.o_proj.activation_scale  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.o_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.q_proj.activation_scale  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.q_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.v_proj.activation_scale  <= modal (most tensors at this size)
	//         34                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.v_proj.weight_scale_inv  <= modal (most tensors at this size)
	//
	// modal size: 2 B (0.000 MiB) shared by the most tensors (476 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 2,097,152 B (2.000 MiB) — raised to the 2 MiB minimum chunk floor.
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"ministral-3-8b-instruct-2512": 2097152,
	"ministral-3-8b-instruct":      2097152, // alias (preset name)

	// === ministral-3-14b-instruct ===
	// repo:    mistralai/Ministral-3-14B-Instruct-2512 @ 6aa4534f7bb46d16753bd12a08b32810a06b7a14
	// tensors: 1,145   total: 15,726,582,880 B (14.65 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         40        83,886,080  80.000 MiB  F8_E4M3 (5120, 16384)    language_model.model.layers.N.mlp.down_proj.weight
	//         40        83,886,080  80.000 MiB  F8_E4M3 (16384, 5120)    language_model.model.layers.N.mlp.gate_proj.weight
	//         40        83,886,080  80.000 MiB  F8_E4M3 (16384, 5120)    language_model.model.layers.N.mlp.up_proj.weight
	//          1     1,342,177,280  1280.000 MiB  BF16   (131072, 5120)   language_model.lm_head.weight
	//          1     1,342,177,280  1280.000 MiB  BF16   (131072, 5120)   language_model.model.embed_tokens.weight
	//         40        20,971,520  20.000 MiB  F8_E4M3 (5120, 4096)     language_model.model.layers.N.self_attn.o_proj.weight
	//         40        20,971,520  20.000 MiB  F8_E4M3 (4096, 5120)     language_model.model.layers.N.self_attn.q_proj.weight
	//         40         5,242,880   5.000 MiB  F8_E4M3 (1024, 5120)     language_model.model.layers.N.self_attn.k_proj.weight
	//         40         5,242,880   5.000 MiB  F8_E4M3 (1024, 5120)     language_model.model.layers.N.self_attn.v_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (1024, 4096)     vision_tower.transformer.layers.N.feed_forward.down_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (4096, 1024)     vision_tower.transformer.layers.N.feed_forward.gate_proj.weight
	//         24         8,388,608   8.000 MiB  BF16   (4096, 1024)     vision_tower.transformer.layers.N.feed_forward.up_proj.weight
	//          1        52,428,800  50.000 MiB  BF16   (5120, 5120)     multi_modal_projector.linear_2.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.k_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.o_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.q_proj.weight
	//         24         2,097,152   2.000 MiB  BF16   (1024, 1024)     vision_tower.transformer.layers.N.attention.v_proj.weight
	//          1        10,485,760  10.000 MiB  BF16   (5120, 1024)     multi_modal_projector.linear_1.weight
	//          1         8,388,608   8.000 MiB  BF16   (1024, 4096)     multi_modal_projector.patch_merger.merging_layer.weight
	//          1         1,204,224   1.148 MiB  BF16   (1024, 3, 14, 14) vision_tower.patch_conv.weight
	//         40            10,240   0.010 MiB  BF16   (5120,)          language_model.model.layers.N.input_layernorm.weight
	//         40            10,240   0.010 MiB  BF16   (5120,)          language_model.model.layers.N.post_attention_layernorm.weight
	//         24             2,048   0.002 MiB  BF16   (1024,)          vision_tower.transformer.layers.N.attention_norm.weight
	//         24             2,048   0.002 MiB  BF16   (1024,)          vision_tower.transformer.layers.N.ffn_norm.weight
	//          1            10,240   0.010 MiB  BF16   (5120,)          language_model.model.norm.weight
	//          1             2,048   0.002 MiB  BF16   (1024,)          multi_modal_projector.norm.weight
	//          1             2,048   0.002 MiB  BF16   (1024,)          vision_tower.ln_pre.weight
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.down_proj.activation_scale  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.down_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.gate_proj.activation_scale  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.gate_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.up_proj.activation_scale  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.mlp.up_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.k_proj.activation_scale  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.k_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.o_proj.activation_scale  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.o_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.q_proj.activation_scale  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.q_proj.weight_scale_inv  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.v_proj.activation_scale  <= modal (most tensors at this size)
	//         40                 2   0.000 MiB  BF16   ()               language_model.model.layers.N.self_attn.v_proj.weight_scale_inv  <= modal (most tensors at this size)
	//
	// modal size: 2 B (0.000 MiB) shared by the most tensors (560 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 2,097,152 B (2.000 MiB) — raised to the 2 MiB minimum chunk floor.
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"ministral-3-14b-instruct-2512": 2097152,
	"ministral-3-14b-instruct":      2097152, // alias (preset name)

	// === falcon-7b ===
	// repo:    tiiuae/falcon-7b @ ec89142b67d748a1865ea4451372db8313ada0d8
	// tensors: 196   total: 14,434,379,520 B (13.44 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       165,183,488  157.531 MiB  BF16   (4544, 18176)    transformer.h.N.mlp.dense_4h_to_h.weight  <= modal (counted as 32 MiB cap)
	//         32       165,183,488  157.531 MiB  BF16   (18176, 4544)    transformer.h.N.mlp.dense_h_to_4h.weight  <= modal (counted as 32 MiB cap)
	//         32        42,459,136  40.492 MiB  BF16   (4672, 4544)     transformer.h.N.self_attention.query_key_value.weight  <= modal (counted as 32 MiB cap)
	//         32        41,295,872  39.383 MiB  BF16   (4544, 4544)     transformer.h.N.self_attention.dense.weight  <= modal (counted as 32 MiB cap)
	//          1       590,938,112  563.562 MiB  BF16   (65024, 4544)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       590,938,112  563.562 MiB  BF16   (65024, 4544)    transformer.word_embeddings.weight  <= modal (counted as 32 MiB cap)
	//         32             9,088   0.009 MiB  BF16   (4544,)          transformer.h.N.input_layernorm.bias
	//         32             9,088   0.009 MiB  BF16   (4544,)          transformer.h.N.input_layernorm.weight
	//          1             9,088   0.009 MiB  BF16   (4544,)          transformer.ln_f.bias
	//          1             9,088   0.009 MiB  BF16   (4544,)          transformer.ln_f.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (130 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"falcon-7b": 33554432,

	// === falcon-7b-instruct ===
	// repo:    tiiuae/falcon-7b-instruct @ 8782b5c5d8c9290412416618f36a133653e85285
	// tensors: 196   total: 14,434,379,520 B (13.44 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         32       165,183,488  157.531 MiB  BF16   (4544, 18176)    transformer.h.N.mlp.dense_4h_to_h.weight  <= modal (counted as 32 MiB cap)
	//         32       165,183,488  157.531 MiB  BF16   (18176, 4544)    transformer.h.N.mlp.dense_h_to_4h.weight  <= modal (counted as 32 MiB cap)
	//         32        42,459,136  40.492 MiB  BF16   (4672, 4544)     transformer.h.N.self_attention.query_key_value.weight  <= modal (counted as 32 MiB cap)
	//         32        41,295,872  39.383 MiB  BF16   (4544, 4544)     transformer.h.N.self_attention.dense.weight  <= modal (counted as 32 MiB cap)
	//          1       590,938,112  563.562 MiB  BF16   (65024, 4544)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1       590,938,112  563.562 MiB  BF16   (65024, 4544)    transformer.word_embeddings.weight  <= modal (counted as 32 MiB cap)
	//         32             9,088   0.009 MiB  BF16   (4544,)          transformer.h.N.input_layernorm.bias
	//         32             9,088   0.009 MiB  BF16   (4544,)          transformer.h.N.input_layernorm.weight
	//          1             9,088   0.009 MiB  BF16   (4544,)          transformer.ln_f.bias
	//          1             9,088   0.009 MiB  BF16   (4544,)          transformer.ln_f.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (130 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"falcon-7b-instruct": 33554432,

	// === falcon-40b ===
	// repo:    tiiuae/falcon-40b @ 05ab2ee8d6b593bdbab17d728de5c028a7a94d83
	// tensors: 484   total: 83,671,941,120 B (77.93 GiB)
	//
	//      count       size(bytes)        size  dtype  shape            tensor
	//         60       536,870,912  512.000 MiB  BF16   (8192, 32768)    transformer.h.N.mlp.dense_4h_to_h.weight  <= modal (counted as 32 MiB cap)
	//         60       536,870,912  512.000 MiB  BF16   (32768, 8192)    transformer.h.N.mlp.dense_h_to_4h.weight  <= modal (counted as 32 MiB cap)
	//         60       150,994,944  144.000 MiB  BF16   (9216, 8192)     transformer.h.N.self_attention.query_key_value.weight  <= modal (counted as 32 MiB cap)
	//         60       134,217,728  128.000 MiB  BF16   (8192, 8192)     transformer.h.N.self_attention.dense.weight  <= modal (counted as 32 MiB cap)
	//          1     1,065,353,216  1016.000 MiB  BF16   (65024, 8192)    lm_head.weight  <= modal (counted as 32 MiB cap)
	//          1     1,065,353,216  1016.000 MiB  BF16   (65024, 8192)    transformer.word_embeddings.weight  <= modal (counted as 32 MiB cap)
	//         60            16,384   0.016 MiB  BF16   (8192,)          transformer.h.N.ln_attn.bias
	//         60            16,384   0.016 MiB  BF16   (8192,)          transformer.h.N.ln_attn.weight
	//         60            16,384   0.016 MiB  BF16   (8192,)          transformer.h.N.ln_mlp.bias
	//         60            16,384   0.016 MiB  BF16   (8192,)          transformer.h.N.ln_mlp.weight
	//          1            16,384   0.016 MiB  BF16   (8192,)          transformer.ln_f.bias
	//          1            16,384   0.016 MiB  BF16   (8192,)          transformer.ln_f.weight
	//
	// modal size: 33,554,432 B (32.000 MiB) shared by the most tensors (242 tensors at
	// this size, tensors larger than 32 MiB counted as 32 MiB).
	// recommended: 33,554,432 B (32.000 MiB).
	// The full tensor layout above is retained verbatim; no rows are filtered out.
	"falcon-40b": 33554432,
}
