# Example AutoIndexer configuration for static data source

apiVersion: kaito.io/v1alpha1
kind: AutoIndexer
metadata:
  name: example-static-autoindexer
  namespace: default
spec:
  # Target index name in the RAG engine
  indexName: "example-documents"
  
  # Reference to the RAG engine
  ragEngineRef:
    name: "my-ragengine"
    namespace: "default"
  
  # Static data source configuration
  dataSource:
    type: Static
    static:
      content:
        - "This is the first example document that will be indexed in the RAG engine."
        - "This is the second example document with different content for testing."
        - "A third document to demonstrate batch processing capabilities."
      urls:
        - "https://raw.githubusercontent.com/kaito-project/kaito/main/README.md"
  
  # Optional: Schedule for periodic re-indexing (creates CronJob)
  # schedule: "0 2 * * *"  # Daily at 2 AM
  
  # Optional: Retry policy for failed indexing attempts
  retryPolicy:
    maxAttempts: 3
    initialDelay: "1s"
    backoffMultiplier: 2.0
    maxDelay: "60s"
  
  # Optional: Resource requirements for the indexing job
  resourcePolicy:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  
  # Optional: Credentials for accessing data sources
  # credentials:
  #   secretRef:
  #     name: "indexing-secrets"

---

# Example with scheduled indexing (CronJob)
apiVersion: kaito.io/v1alpha1
kind: AutoIndexer
metadata:
  name: scheduled-autoindexer
  namespace: default
spec:
  indexName: "scheduled-documents"
  
  ragEngineRef:
    name: "my-ragengine"
    namespace: "default"
  
  dataSource:
    type: Static
    static:
      urls:
        - "https://api.github.com/repos/kaito-project/kaito/readme"
        - "https://raw.githubusercontent.com/kaito-project/kaito/main/docs/architecture.md"
  
  # Schedule for daily indexing at 3 AM
  schedule: "0 3 * * *"
  
  retryPolicy:
    maxAttempts: 5
    initialDelay: "2s"
  
  resourcePolicy:
    requests:
      cpu: "200m"
      memory: "512Mi"

---

# Example with credentials for authenticated data sources
apiVersion: kaito.io/v1alpha1
kind: AutoIndexer
metadata:
  name: authenticated-autoindexer
  namespace: default
spec:
  indexName: "private-documents"
  
  ragEngineRef:
    name: "my-ragengine"
    namespace: "default"
  
  dataSource:
    type: Static
    static:
      urls:
        - "https://private-api.example.com/documents/doc1.txt"
        - "https://private-api.example.com/documents/doc2.json"
  
  credentials:
    secretRef:
      name: "api-credentials"
    # The secret should contain:
    # data:
    #   config: |
    #     {
    #       "http_auth": {
    #         "username": "api-user",
    #         "password": "api-password"
    #       },
    #       "headers": {
    #         "Authorization": "Bearer token123",
    #         "X-API-Key": "your-api-key"
    #       }
    #     }

---

# Supporting secret for authenticated example
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded JSON configuration
  config: ewogICJodHRwX2F1dGgiOiB7CiAgICAidXNlcm5hbWUiOiAiYXBpLXVzZXIiLAogICAgInBhc3N3b3JkIjogImFwaS1wYXNzd29yZCIKICB9LAogICJoZWFkZXJzIjogewogICAgIkF1dGhvcml6YXRpb24iOiAiQmVhcmVyIHRva2VuMTIzIiwKICAgICJYLUFQSS1LZXkiOiAieW91ci1hcGkta2V5IgogIH0KfQ==
