apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: phi-4-prefill-pool-epp
spec:
  host: phi-4-prefill-pool-epp
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: phi-4-decode-pool-epp
spec:
  host: phi-4-decode-pool-epp
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
