apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: phi-4-inferencepool-epp
spec:
  host: phi-4-inferencepool-epp.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
