---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kaito.sh
  resources:
  - autoindexers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kaito.sh
  resources:
  - autoindexers/finalizers
  verbs:
  - update
- apiGroups:
  - kaito.sh
  resources:
  - autoindexers/status
  verbs:
  - get
  - list
  - patch
  - update
