# Default values for kaito.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: brfoletest.azurecr.io/autoindexer
  pullPolicy: IfNotPresent
  tag: 0.6.0
imagePullSecrets: []
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"
# Knative logging configuration
logging:
  level: "error"
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
presetAutoIndexerRegistryName: "brfoletest.azurecr.io"
presetAutoIndexerImageName: "autoindexer-service"
presetAutoIndexerImageTag: v0.0.1
clusterName: autoindexer-test
