# Default values for KAITO.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: aimodelsregistrytest.azurecr.io/bangqi-ragengine
  pullPolicy: IfNotPresent
  tag: 0.0.2
imagePullSecrets: []
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"
webhook:
  port: 9443
# Knative logging configuration
logging:
  level: "error"
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
# Values can be "azure" or "aws"
cloudProviderName: "azure"
presetRagRegistryName: "aimodelsregistrytest.azurecr.io"
presetRagImageName: "ragengine-qdrant-service"
presetRagImageTag: 0.0.2