# Default values for kaito.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: mcr.microsoft.com/aks/kaito/workspace
  pullPolicy: IfNotPresent
  tag: 0.6.0
imagePullSecrets: []
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"
featureGates:
  vLLM: true
  disableNodeAutoProvisioning: false
  gatewayAPIInferenceExtension: false
webhook:
  port: 9443
# Knative logging configuration
logging:
  level: "error"
presetRegistryName: mcr.microsoft.com/aks/kaito
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
# Values can be "azure" or "aws" or "arc"
cloudProviderName: "azure"
clusterName: "kaito"
# Set values for the Flux controller to only install the Helm controller
flux2:
  helmController:
    create: true
  sourceController:
    create: true
  imageAutomationController:
    create: false
  imageReflectionController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false
