apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-phi-3-medium
resource:
  instanceType: <your-vm-sku>
  preferredNodes:
    - <your-arc-node-name>
  labelSelector:
    matchLabels:
      apps: llm-inference
inference:
  preset:
    name: phi-3-medium-4k-instruct
