apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-deepseek-r1-distill-llama-8b
resource:
  instanceType: <your-vm-sku>
  preferredNodes:
    - <your-arc-node-name>
  labelSelector:
    matchLabels:
      apps: llm-inference
inference:
  preset:
    name: "deepseek-r1-distill-llama-8b"
    
