apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-deepseek-v3--1
resource:
  count: 6
  instanceType: Standard_NC80adis_H100_v5
  labelSelector:
    matchLabels:
      apps: deepseek-v3--1
inference:
  config: "ds-inference-params"
  preset:
    name: "deepseek-v3.1"
    presetOptions:
      modelAccessSecret: hf-token
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-token
type: Opaque
data:
  HF_TOKEN: <base64-encoded-huggingface-token>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-inference-params
data:
  inference_config.yaml: |
    vllm:
      cpu-offload-gb: 0
      gpu-memory-utilization: 0.95
      swap-space: 4
      max-model-len: 163840
