apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-deepseek-r1
resource:
  count: 6
  instanceType: Standard_NC80adis_H100_v5
  labelSelector:
    matchLabels:
      apps: deepseek-r1
inference:
  config: "ds-inference-params"
  preset:
    name: "deepseek-r1-0528"
    presetOptions:
      modelAccessSecret: hf-token
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-token
type: Opaque
data:
  HF_TOKEN: <base64-encoded-huggingface-token>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-inference-params
data:
  inference_config.yaml: |
    # Maximum number of steps to find the max available seq len fitting in the GPU memory.
    max_probe_steps: 6

    vllm:
      cpu-offload-gb: 0
      gpu-memory-utilization: 0.95
      swap-space: 4
      max-model-len: 163840
