apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-llama-2-7b
resource:
  instanceType: "Standard_NC24ads_A100_v4"
  labelSelector:
    matchLabels:
      apps: llama-2-7b
inference:
  preset:
    name: "llama-2-7b"
    accessMode: private
    presetOptions:
      image: <YOUR IMAGE URL>
