apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-tuning-falcon-7b-dolly-oai
resource:
  instanceType: "Standard_NC12s_v3"
  labelSelector:
    matchLabels:
      app: tuning-falcon-7b
tuning:
  preset:
    name: falcon-7b
  method: qlora
  config: qlora-params-template  # Your configMap containing tuning arguments
  input:
    urls:
      - "https://huggingface.co/datasets/philschmid/dolly-15k-oai-style/resolve/main/data/train-00000-of-00001-54e3756291ca09c6.parquet?download=true"
  output:
    image: "ACR_REPO_HERE.azurecr.io/IMAGE_NAME_HERE:0.0.1" # Tuning Output ACR Path
    imagePushSecret: ACR_REGISTRY_SECRET_HERE
