apiVersion: v1
kind: ConfigMap
metadata:
  name: kaito-logging-config
  namespace: {{ .Release.Namespace }}
data:
  loglevel.controller: {{ .Values.logging.level | quote }}
  loglevel.webhook: {{ .Values.logging.level | quote }}
  loglevel.autoscaler: {{ .Values.logging.level | quote }}
  loglevel.queueproxy: {{ .Values.logging.level | quote }}
  loglevel.activator: {{ .Values.logging.level | quote }}
  loglevel.hpaautoscaler: {{ .Values.logging.level | quote }}
  loglevel.certcontroller: {{ .Values.logging.level | quote }}
  loglevel.istiocontroller: {{ .Values.logging.level | quote }}
  zap-logger-config: |
    {
      "level": {{ .Values.logging.level | quote }},
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
