apiVersion: v1
kind: Secret
metadata:
  name: autoindexer-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaito.labels" . | nindent 4 }}
data:
   server-key.pem: ""
   server-cert.pem: ""
   ca-cert.pem: ""
