apiVersion: kaito.sh/v1alpha1
kind: RAGEngine
metadata:
  name: ragengine-start1
spec:
  compute:
    instanceType: "Standard_NC6s_v3"  
    labelSelector:
      matchLabels:
        apps: phi-3
  embedding:
    local:
      modelID: "BAAI/bge-small-en-v1.5"
  inferenceService:
    url: "http://workspace-phi-3-medium-128k-bq-start.default.svc.cluster.local/v1/completions"
