apiVersion: kaito.sh/v1alpha1
kind: RAGEngine
metadata:
  name: ragengine
spec:
  compute:
    instanceType: "Standard_NC24ads_A100_v4"  
    labelSelector:
      matchLabels:
        apps: ragengine-example
  embedding:  
    local:
      modelID: "BAAI/bge-small-en-v1.5"       
  inferenceService:
    url: "<inference-url>/v1/chat/completions"
    # phi3-mini-4k-instruct example contextWindowSize
    # set to your models context window size
    contextWindowSize: 4000
