apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-nvme-disk
  labels:
    {{- include "kaito.labels" . | nindent 4 }}
parameters:
  local.csi.azure.com/vg: containerstorage
provisioner: local.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true