name: Publish helm chart

on:
  repository_dispatch:
    types: [ publish-helm-chart ]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  packages: write
  contents: write
  actions: read
  deployments: read
  pull-requests: read

jobs:
  publish-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.client_payload.tag }}

      - name: Publish Workspace Helm chart
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 # v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts/kaito
          target_dir: charts/kaito
          linting: off

  create-release:
    runs-on: ubuntu-latest
    needs: [ publish-helm ]
    steps:
      - name: 'Dispatch release tag to create a release'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: create-release
          client-payload: '{"tag": "${{ github.event.client_payload.tag }}"}'

