name: License Header

concurrency:
  group:  ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0

      - name: Check Go file headers
        run: |
          boilerplate_file="hack/boilerplate.go.txt"
          boilerplate_content=$(cat "$boilerplate_file")
          boilerplate_lines=$(awk 'END{print NR}' "$boilerplate_file")

          # Find all .go files
          mapfile -t go_files < <(find . -type f -name '*.go' -not -name '*.deepcopy.go')

          exit_code=0
          failed_files=""

          for file in "${go_files[@]}"; do
            # Get the header of the current file
            header=$(head -n "$boilerplate_lines" "$file")

            # Compare header with boilerplate
            if [ "$header" != "$boilerplate_content" ]; then
              echo "::error file=$file::File '$file' is missing or has an incorrect boilerplate header."
              exit_code=1
            fi
          done

          if [ $exit_code -ne 0 ]; then
            echo "Please add the content of '$boilerplate_file' to the beginning of the listed files."
          else
            echo "Boilerplate check passed for all Go files."
          fi
          exit $exit_code
