name: Python Lint

concurrency:
  group:  ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Ruff linter
      - uses: astral-sh/ruff-action@v3
        with:
          # Update output format to enable automatic inline annotations.
          args: check --output-format=github .

      # Check formatting without making changes.
      - name: Ruff format check
      - run: ruff format --check .

