name: Python Lint

on:
  push:
    paths:
      - '**.py'
    branches:
      - main
      - e2e-fix
  pull_request:
    paths:
      - '**.py'
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          # Update output format to enable automatic inline annotations.
          args: check --output-format=github .

      # Check formatting without making changes.
      - name: Ruff format check
        run: ruff format --check .
