name: Markdown link check

on:
  pull_request:
    paths:
      - "**.md"
      - "docs/**"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          # this will only show errors in the output
          use-quiet-mode: "yes"
          # this will show detailed HTTP status for checked links
          use-verbose-mode: "yes"
          config-file: ".github/markdown.links.config.json"
