name: Publish ragengine helm chart

on:
  repository_dispatch:
    types: [ publish-ragengine-helm-chart ]

permissions:
  id-token: write # This is required for requesting the JWT
  packages: write
  contents: write
  actions: read
  deployments: read
  pull-requests: read

jobs:
  publish-ragengine-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.client_payload.tag }}

      - name: Package ragengine helm chart
        run: |
          mkdir -p packaged-rag
          mv charts/kaito/ragengine packaged-rag

      - name: Publish ragengine helm chart
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 # v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: packaged-rag
          target_dir: charts/kaito
          linting: off

 