name: Publish workspace helm chart

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish (e.g. v0.6.1)'
        required: true
  repository_dispatch:
    types: [ publish-workspace-helm-chart ]

permissions:
  id-token: write # This is required for requesting the JWT
  packages: write
  contents: write
  actions: read
  deployments: read
  pull-requests: read

jobs:
  publish-workspace-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.client_payload.tag || github.event.inputs.tag }}

      - name: Package workspace helm chart
        run: |
          mkdir -p packaged-ws
          mv charts/kaito/workspace packaged-ws

      - name: Publish workspace helm chart
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 # v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: packaged-ws
          target_dir: charts/kaito
          linting: off
