name: Publish RAG Service MCR image
on:
  repository_dispatch:
    types: [ publish-rag-service-mcr-image ]

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: 'kaito-rag-service'

jobs:
  build-publish-mcr-image:
    runs-on:
      labels: [ "self-hosted", "1ES.Pool=1es-aks-kaito-agent-pool-ubuntu" ]
    environment: publish-mcr
    steps:
      - name: Set Image tag
        run: |
          ver=${{ github.event.client_payload.tag }}
          echo "IMG_TAG=${ver#"v"}" >> $GITHUB_ENV

      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.event.client_payload.tag }}

      - name: Authenticate to ACR
        run: |
          az login --identity
          az acr login -n ${{ secrets.KAITO_MCR_REGISTRY }}

      - name: 'Build and Publish RAG Service to MCR'
        id: Publish
        run: |
          OUTPUT_TYPE=type=registry make docker-build-ragservice
        env:
          VERSION: ${{ github.event.client_payload.tag }}
          REGISTRY: ${{ secrets.KAITO_MCR_REGISTRY }}/public/aks/kaito
          RAGENGINE_SERVICE_IMG_NAME: kaito-rag-service
          RAGENGINE_SERVICE_IMG_TAG: ${{ github.event.client_payload.tag }}

  publish-helm-chart:
    runs-on: ubuntu-latest
    needs: [ build-publish-mcr-image ]
    steps:
      - name: 'Dispatch release tag for ragengine helm chart'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: publish-ragengine-helm-chart
          client-payload: '{"tag": "${{ github.event.client_payload.tag }}"}' 