name: Trivy vulnerability scanner
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-scan:
    name: Scan ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: docker-build-workspace
            image: test/workspace:latest
            registry: test
          - target: docker-build-ragengine
            image: test/ragengine:latest
            registry: test
          - target: docker-build-ragservice
            image: test/kaito-rag-service:v0.0.1
            registry: test

    steps:

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build image from Dockerfile
        run: |
          export REGISTRY=${{ matrix.registry }}
          export IMG_TAG=latest
          export OUTPUT_TYPE="type=docker"
          export ARCH="amd64"
          make ${{ matrix.target }} BUILD_FLAGS="--target dependencies"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # v0.32.0
        with:
          image-ref: ${{ matrix.image }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN"
