name: unit-tests-ragengine

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths-ignore: ["docs/**", "**.md", "**.mdx", "**.png", "**.jpg"]
  pull_request:
    branches: [main, release-**]
    paths-ignore: ["docs/**", "**.md", "**.mdx", "**.png", "**.jpg"]

permissions:
  contents: read
  packages: write

env:
  GO_VERSION: "1.24"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    environment: unit-tests
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true

      - name: Check out the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0

      - name: Run unit tests
        run: |
          make rag-service-test

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
