name: unit-tests-ragengine

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths-ignore: ["docs/**", "**.md", "**.mdx", "**.png", "**.jpg"]
  pull_request:
    branches: [main, release-**]
    paths-ignore: ["docs/**", "**.md", "**.mdx", "**.png", "**.jpg"]

permissions:
  contents: read
  packages: write

env:
  GO_VERSION: "1.24"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    environment: unit-tests
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true

      - name: Check out the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
          fetch-depth: 0

      - name: Run unit tests
        run: |
          make rag-service-test

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
